apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: accoount-container
        image: transaction/services:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
