apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: accoount-container
        image: account/services:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
