apiVersion: apps/v1
kind: Deployment
metadata:
  name: statement-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statement
  template:
    metadata:
      labels:
        app: statement
    spec:
      containers:
      - name: accoount-container
        image: statement/services:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3005
